site_name: Piazza Documentation
docs_dir: documents
markdown_extensions:
  - toc:
      permalink: True
      separator: "_"
extra_css:
    - css/beachfront.css
extra_javascript:
    - js/beachfront.js

pages:
  - Home: 'index.md'
  - About:
    - 'about/intro.md'
    - 'about/legal.md'
    - 'about/support.md'
  - Developer Guide:
    - Home: 'devguide/index.md'
    - Introduction: 'devguide/01-introduction.md'
    - Piazza Core Overview: 'devguide/02-pz-core.md'
    - Prerequisites for Using Piazza: 'devguide/03-jobs.md'
    - Job Manager: 'devguide/05-pz-jobmanager.md'
    - Logger: 'devguide/06-pz-logger.md'
    - Gateway: 'devguide/07-pz-gateway.md'
    - SAK (Development/Debug UI Tool): 'devguide/08-pz-sak.md'
    - Access: 'devguide/09-pz-access.md'
    - Ingest: 'devguide/10-pz-ingest.md'
    - Piazza Search Services: 'devguide/12-pz-search-services.md'
    - Identity and Access Management (IDAM): 'devguide/13-pz-idam.md'
    - Piazza Service Controller: 'devguide/14-pz-servicecontroller.md'
    - Workflow Service: 'devguide/15-pz-workflow.md'
    - Job Common: 'devguide/16-job-common.md'
    - Conventions: 'devguide/17-conventions.md'
  - User Guide:
    - Home: 'userguide/index.md'
    - Introduction: 'userguide/1-introduction.md'
    - Hello, Piazza!: 'userguide/2-hello.md'
    - Data Load and Access: 'userguide/3-load-access.md'
    - Search: 'userguide/4-search.md'
    - User Services: 'userguide/5-userservices.md'
    - Workflow Service: 'userguide/6-workflow.md'
    - End-to-End Example: 'userguide/7-endtoend.md'
    - Additional Notes and FAQs: 'userguide/8-notes.md'
