site_name: Piazza Documentation
docs_dir: documents
markdown_extensions:
  - toc:
    permalink: True
    separator: "_"
pages:
  - Home: 'index.markdown'
  - About:
    - 'common/intro.markdown'
    - 'common/legal.markdown'
    - 'common/support.markdown'
  - Developer Guide:
    - 'devguide/index.markdown'
    - 'devguide/01_1-process.markdown'
    - 'devguide/01-introduction.markdown'
    - 'devguide/02-pz-core.markdown'
    - 'devguide/03-jobs.markdown'
    - 'devguide/04-job-workflow.markdown'
    - 'devguide/05-pz-jobmanager.markdown'
    - 'devguide/06-pz-logger.markdown'
    - 'devguide/07-pz-gateway.markdown'
    - 'devguide/08-pz-sak.markdown'
    - 'devguide/09-pz-access.markdown'
    - 'devguide/10-pz-ingest.markdown'
    - 'devguide/11-pz-search-metadata-ingest.markdown'
    - 'devguide/12-pz-search-services.markdown'
    - 'devguide/13-pz-idam.markdown'
    - 'devguide/14-pz-servicecontroller.markdown'
    - 'devguide/15-pz-workflow.markdown'
    - 'devguide/16-job-common.markdown'
    - 'devguide/17-conventions.markdown'
    - 'devguide/18_1-http.markdown'
  - User Guide:
    - 'userguide/index.markdown'
    - 'userguide/1-introduction.markdown'
    - 'userguide/2-hello.markdown'
    - 'userguide/3-load-access.markdown'
    - 'userguide/4-search.markdown'
    - 'userguide/5-userservices.markdown'
    - 'userguide/6-workflow.markdown'
    - 'userguide/7-endtoend.markdown'
    - 'userguide/8-notes.markdown'
